### ISSUE TITLE
Got "AJAX handler 'onAddtoCart' was not found" while adding item to cart

### ISSUE THREAD

**Issue by hyourinseta** [scottbedard/shop#1]
I'm getting popup with this error message while adding item to cart.
"AJAX handler 'onAddtoCart' was not found."

I've searched over Internet, and they said that I've not added the component to the page. But I've done that.

I'm new to October CMS and trying to add shop plugin to my project. 

Could you help me?
Thanks and sorry if my english is bad.

**Comment by scottbedard** [comment]
If you're sure the cart component is already attached, try changing 'onAddtoCart' to 'onAddToCart' (capitolize the first T). Ajax handlers might be case-sensitive, let me know if this helps!

**Comment by hyourinseta** [comment]
Sorry, it was typo. The error truly said 'onAddToCart' was not found.
I tried product.htm pages at https://github.com/scottbedard/shop-theme but still stuck.

It still can't find the ajax handler. I'm curious about the way I installed your plugin.
Do you have any installation docs of your plugin? Or could you tell me the way? So far I just install plugins from the october plugins page. But I've just installed external plugin manually for the first time.

**Comment by scottbedard** [comment]
The ajax handler resides within the Cart component, so you'll need to make sure that component is included on every page that interacts with the shop. The best place to put it would be in your layout file.

And there are currently no installation docs, because the plugin is still being created. Once I publish the first release i'll make more documentation.

**Comment by hyourinseta** [comment]
I've included the component to the page I want. But everytime I add a product to cart, the error remains.

Could you tell me the way to install your plugin manually?
I used artisan plugin:refresh Bedard.Shop but I got this error message :

[ErrorException]               
  Undefined index: backup_total

What did I miss?
I'm afraid that the way I installed your plugin was wrong.

**Comment by scottbedard** [comment]
That is likely a bug with how the demo-data is being seeded. Please keep in mind that this plugin is still being developed, it's not even to beta yet. I don't expect this to be completely free of bugs while I'm working on it.

**Comment by hyourinseta** [comment]
Ok, I'll wait the release. Thanks for your helps and responses.
Hope it'll be released soon :)
